"use client";
import {useEffect,useMemo,useState} from "react";
import {Database,Send,Sparkles,Building2,Globe2,ChevronDown,ChevronUp,Target,ShieldCheck} from "lucide-react";
const fmt=n=>new Intl.NumberFormat("ko-KR").format(Math.round(n)); const clamp=n=>Math.max(0,Math.min(100,n));
export default function Home(){
 const[d,setD]=useState(null),[input,setInput]=useState(""),[detail,setDetail]=useState(false),[premium,setPremium]=useState(5000),[limit,setLimit]=useState(3000000),[consent,setConsent]=useState(true);
 const[msgs,setMsgs]=useState([{role:"ai",text:"궁금한 상품을 말씀해 주세요. 우리 회사 고객과 외부 시장을 나눠서 반응과 근거를 비교해드릴게요."}]);
 useEffect(()=>{fetch("/market.json").then(r=>r.json()).then(setD)},[]);
 const sim=useMemo(()=>{if(!d)return null;const m=d.months[d.latest],regions=[...m.evRegions].sort((a,b)=>b.value-a.value);const price=clamp(78-(premium-3000)/190),cover=clamp(48+(limit-1000000)/140000),friction=consent?55:72;
 // INTERNAL MOCK: schema-compatible placeholder until company data arrives. Scores are deliberately labeled SYNTHETIC.
 const internal={base:124600,eligible:31800,score:Math.round(clamp(68+cover*.17+price*.10+friction*.05-20)),segments:["EV 보유 + 갱신 2회 이상","월 주행거리 상위군","기존 특약 2개 이상"],reasons:["당사 EV 고객 중 장기 유지·보장 확장 성향이 높은 군에서 상대 반응이 높음","주행량이 많을수록 배터리 관련 비용 불확실성에 대한 보장 니즈가 커지는 것으로 가정","기존 특약 가입 이력이 있는 고객은 추가 보장 수용성이 높다는 가정"]};
 const external={base:m.evPassengerPrivate,eligible:Math.round(m.evPassengerPrivate*.43),score:Math.round(clamp(61+cover*.14+price*.12+friction*.03-16)),segments:[`${regions[0].name}·${regions[1].name} 등 EV 집중 지역`,"EV 장기보유 가상군","가격 대비 보장가치 중시 가상군"],reasons:[`2026.08 EV 승용·비사업용 ${fmt(m.evPassengerPrivate)}대가 관측됨`,`EV 보유는 ${regions.slice(0,3).map(x=>x.name).join("·")}에 상대적으로 집중`,`개인 단위 결합 데이터가 없어 가격·보장 민감도는 합성 가정으로 적용`]};
 return{m,regions,internal,external}},[d,premium,limit,consent]);
 if(!sim)return <div className="loading">Virtual Auto Market loading…</div>; const{internal,external,m}=sim;
 const answer=q=>{const t=q.replace(/,/g,"");const won=t.match(/(?:보험료|월보험료)[^0-9]*(\d+)/);if(won){let v=+won[1];if(v<100)v*=1000;setPremium(Math.max(2000,Math.min(12000,v)))}const man=t.match(/(?:보장|한도)[^0-9]*(\d+)\s*(?:만)?/);if(man){let v=+man[1];if(v<10000)v*=10000;setLimit(Math.max(1000000,Math.min(10000000,v)))}return `EV 배터리 특약을 기준으로 보면, 우리 회사 고객에서는 EV 보유 고객 중 갱신·주행·기존 특약 이력이 있는 고객군의 상대 반응이 더 높게 나타나는 시나리오입니다. 반면 외부 시장에서는 전체 EV 보유 ${fmt(m.evPassengerPrivate)}대를 기준으로 지역별 EV 집중도와 상품 가격·보장가치를 반영했을 때 선택적인 반응이 예상되는 시뮬레이션입니다. 아래에서 내부 고객과 외부 시장의 근거를 따로 확인할 수 있습니다.`};
 const send=(q=input)=>{q=q.trim();if(!q)return;setMsgs(x=>[...x,{role:"user",text:q},{role:"ai",text:answer(q)}]);setInput("")};
 return <main className="exec"><header className="top"><div><div className="eyebrow">VIRTUAL AUTO MARKET</div><h1>상품 반응을 물어보세요.</h1><p>사내 고객 데이터와 외부 시장을 동시에 시뮬레이션해 비교합니다.</p></div><div className="source"><Database size={14}/> INTERNAL + EXTERNAL</div></header>
 <section className="ask"><div className="askTitle"><Sparkles size={18}/><b>AI Market Simulator</b></div><div className="conversation">{msgs.slice(-3).map((x,i)=><div key={i} className={`bubble ${x.role}`}>{x.text}</div>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="예: EV 배터리 특약 출시하면 반응 어떨까?"/><button><Send size={17}/><span>분석</span></button></form><div className="examples"><button onClick={()=>send("EV 배터리 특약 반응 어떨까?")}>EV 배터리 특약 반응 어떨까?</button><button onClick={()=>send("월 4천원이면 반응 달라져?")}>월 4천원이면?</button><button onClick={()=>send("누구한테 먼저 팔아야 해?")}>핵심 타깃은?</button></div></section>
 <section className="summary"><div className="summaryHead"><span>SIMULATION RESULT</span><h2>EV 배터리 보장 특약</h2><p>월 {fmt(premium)}원 · 보장 {fmt(limit/10000)}만원 · 차량데이터 동의 {consent?"필요":"불필요"}</p></div><div className="compare">
 <article className="side internal"><div className="sideHead"><div className="sideIcon"><Building2/></div><div><span>OUR CUSTOMERS</span><h3>우리 회사 고객</h3></div><b className="badge">INTERNAL · MOCK</b></div><div className="headline"><strong>{internal.score}<small>/100</small></strong><div><b>상대적으로 높은 반응</b><span>현재는 사내데이터가 있다고 가정한 합성 결과</span></div></div><div className="target"><Target/><div><span>우선 공략 고객</span><b>{internal.segments[0]}</b></div></div><div className="evidence"><b>왜 이렇게 보나요?</b>{internal.reasons.map((x,i)=><p key={i}><i>{i+1}</i>{x}</p>)}</div><div className="numbers"><div><span>가정 EV 고객</span><b>{fmt(internal.base)}명</b></div><div><span>탐색 타깃</span><b>{fmt(internal.eligible)}명</b></div></div></article>
 <div className="vs"><span>VS</span></div>
 <article className="side external"><div className="sideHead"><div className="sideIcon"><Globe2/></div><div><span>EXTERNAL MARKET</span><h3>전체 외부 시장</h3></div><b className="badge observed">OBSERVED + SYNTHETIC</b></div><div className="headline"><strong>{external.score}<small>/100</small></strong><div><b>선택적인 반응</b><span>공식 시장통계 + 합성 민감도</span></div></div><div className="target"><Target/><div><span>우선 공략 시장</span><b>{external.segments[0]}</b></div></div><div className="evidence"><b>왜 이렇게 보나요?</b>{external.reasons.map((x,i)=><p key={i}><i>{i+1}</i>{x}</p>)}</div><div className="numbers"><div><span>관측 EV 시장</span><b>{fmt(external.base)}대</b></div><div><span>탐색 시장</span><b>{fmt(external.eligible)}대</b></div></div></article></div>
 <div className="executive"><ShieldCheck/><div><span>EXECUTIVE TAKEAWAY</span><p><b>사내에서는 기존 관계·행동 데이터로 ‘누가 살 가능성이 높은지’를 좁히고, 외부에서는 시장 규모와 구조로 ‘어디에 기회가 큰지’를 봅니다.</b> 두 결과를 함께 사용해 출시 우선순위와 타깃 전략을 결정하는 구조입니다.</p></div></div></section>
 <button className="detailBtn" onClick={()=>setDetail(!detail)}>{detail?"상세 근거 닫기":"분석 로직 · 데이터 출처 보기"}{detail?<ChevronUp/>:<ChevronDown/>}</button>{detail&&<section className="details"><div><b>INTERNAL · 준비 데이터</b><p>고객·차량·주행·사고·계약·특약·디지털 행동·타보험 보유 데이터를 연결하는 구조입니다. 현재 화면의 내부 숫자는 실제 사내값이 아닌 MOCK입니다.</p></div><div><b>EXTERNAL · 현재 연결</b><p>2026.07–08 자동차 등록 통계. 8월 EV 승용·비사업용 {fmt(m.evPassengerPrivate)}대는 관측값이며 개인 단위 반응은 합성값입니다.</p></div><div><b>PREDICTION LAYER</b><p>향후 실제 가입/제안 반응 label이 연결되면 내부 score는 학습모형으로 교체하고, LLM은 숫자를 만들지 않고 근거 설명과 질의 해석만 담당합니다.</p></div></section>}</main>}
