"use client";
import {useEffect,useState} from "react";
import {Database,Send,Sparkles,Building2,Globe2,ChevronDown,ChevronUp,Target,ShieldCheck,Layers3,TrendingUp} from "lucide-react";
const fmt=n=>new Intl.NumberFormat("ko-KR").format(Math.round(n));
const configs={
 ev:{title:"EV 배터리 보장 특약",condition:"EV 배터리 고장·성능저하 보장",intScore:74,extScore:66,intLabel:"높은 관심 가능",extLabel:"선택적 관심 가능",intWho:"EV 보유 · 갱신 2회 이상 · 주행량 상위 고객",extWho:"EV 보유 밀집 지역 · 보장가치 중시 시장",intReasons:["EV 보유 여부와 차량 특성으로 직접 타깃 식별 가능","갱신·기존 특약 이력으로 보장 확장 성향을 구분","주행량·사고·차량가액을 결합해 비용 리스크 체감군 세분화"],extReasons:["EV 승용·비사업용 등록대수를 실제 시장 기준점으로 사용","지역별 EV 보유 규모 차이로 우선 시장을 구분","개인 반응 데이터가 없어 가격·보장 민감도는 합성 가정"]},
 driver:{title:"운전자보험 연계판매",condition:"자동차보험 고객 대상 운전자 보장 Cross-sell",intScore:71,extScore:58,intLabel:"타깃 선별 시 기회",extLabel:"시장 기회 탐색",intWho:"자동차보험 단독 · 장기보험 미보유 · 활동성 높은 고객",extWho:"자가용 승용 보유 · 경제활동 연령 중심 시장",intReasons:["자동차보험 계약과 타상품 보유를 결합해 단독고객 식별","주행·사고·갱신 데이터로 위험 노출 세분화","디지털 행동·상담 이력으로 제안 접점 고객 우선화"],extReasons:["전체 자동차 보유 규모와 성·연령 분포로 잠재시장 파악","차종·용도별 등록 구조로 시장 구성 비교","보험 가입 여부는 외부 등록통계에 없어 개인 타깃은 합성 추정"]},
 mileage:{title:"주행거리 기반 신특약",condition:"저주행 고객 보험료 혜택 확대",intScore:78,extScore:55,intLabel:"명확한 타깃 가능",extLabel:"추가 데이터 필요",intWho:"저주행 · 안전운전 · 갱신 유지 고객",extWho:"자가용 승용 보유 시장",intReasons:["실제 주행거리와 UBI 안전점수로 대상군 직접 정의","사고·손해율과 결합해 혜택 대상 위험도 비교","기존 마일리지 특약 이력으로 전환 여지 구분"],extReasons:["등록통계로 자가용 승용 시장 규모는 관측 가능","개별 차량의 실제 주행거리는 현재 외부 데이터에 없음","주행거리 외부 통계 연결 시 시장 반응 근거 강화 가능"]},
 age:{title:"연령 타깃 시장 분석",condition:"연령 조건별 당사 고객과 전체 자동차 시장 비교",intScore:69,extScore:64,intLabel:"고객구성 비교 필요",extLabel:"시장규모 확인 가능",intWho:"질의 연령대에 해당하는 당사 자동차보험 고객",extWho:"질의 연령대의 개인 자동차 보유 시장",intReasons:["사내 고객 연령과 계약·차량·손해 데이터를 결합해 반응 차이 분석","동일 연령 내 갱신·채널·상품보유에 따라 세부 타깃 구성","내부 실데이터 연결 전 수치는 MOCK"],extReasons:["공식 성별·연령별 자동차 등록 통계를 활용","연령대별 보유 규모를 대한민국 전체 기준으로 비교","상품 반응 자체는 관측되지 않아 반응지수는 SYNTHETIC"]},
 newcar:{title:"신차 시장 기회 분석",condition:"신규등록 흐름을 활용한 시장 진입·타깃 분석",intScore:67,extScore:70,intLabel:"접점 타이밍 중요",extLabel:"시장 흐름 관측 가능",intWho:"신차 계약 · 신규 유입 · 갱신 전환 고객",extWho:"최근 신규등록이 활발한 승용 시장",intReasons:["당사 신계약·차량변경 시점을 활용해 신차 고객 식별","신차가액·채널·특약구성을 결합해 제안 가능성 분석","실제 내부 계약 데이터 연결 후 정밀화"],extReasons:["2026년 월별 신규등록 흐름을 실제 관측값으로 사용","승용 신규등록과 전체 신규등록 추이를 분리해 비교","시장 유입 규모를 통해 신상품 제안 타이밍을 탐색"]},
 generic:{title:"맞춤 시장 시뮬레이션",condition:"자연어 질의 조건을 해석해 고객·시장 분석 구성",intScore:68,extScore:60,intLabel:"사내 데이터 기반 분석",extLabel:"시장 구조 기반 분석",intWho:"질의 조건에 부합하는 당사 고객군",extWho:"질의 조건에 부합하는 국내 자동차 보유 시장",intReasons:["고객·차량·주행·사고·계약·특약 데이터를 질의 조건에 맞춰 조합","행동·갱신·디지털 접점으로 고객군 차이를 비교","실데이터 연결 후 질의마다 타깃과 근거를 동적 산출"],extReasons:["등록·성별·연령·지역·차종·연료·용도 데이터를 조합","당사 고객 구성과 대한민국 전체 시장 차이를 비교","개인 단위 결합이 없는 항목은 SYNTHETIC으로 구분"]}}
function intent(q){if(/배터리|전기차|\bEV\b/i.test(q))return"ev";if(/운전자보험|연계판매|크로스셀/.test(q))return"driver";if(/주행거리|마일리지|저주행|UBI/.test(q))return"mileage";if(/신차|신규등록|새차/.test(q))return"newcar";if(/\d{2}대|연령|나이/.test(q))return"age";return"generic"}
export default function Home(){const[d,setD]=useState(null),[input,setInput]=useState(""),[detail,setDetail]=useState(false),[key,setKey]=useState("ev"),[query,setQuery]=useState("EV 배터리 특약 반응 어떨까?");const[msgs,setMsgs]=useState([{role:"ai",text:"질문을 입력하면 그 조건에 맞춰 아래 분석 대시보드 전체를 다시 구성합니다. 당사 고객과 대한민국 전체 시장의 근거는 분리해서 보여드릴게요."}]);useEffect(()=>{fetch("/market.json").then(r=>r.json()).then(setD)},[]);if(!d)return <div className="loading">Virtual Auto Market loading…</div>;const m=d.months[d.latest],s=configs[key],months=Object.keys(d.months).sort(),trend=months.map(x=>({month:+x.slice(4),total:d.months[x].totalStock,new:d.months[x].newTotal}));let extBase=m.totalStock,extTarget=Math.round(extBase*.18),metricLabel="전체 자동차 보유";if(key==="ev"){extBase=m.evPassengerPrivate;extTarget=Math.round(extBase*.43);metricLabel="관측 EV 시장"}if(key==="mileage"||key==="driver"){extBase=m.passengerPrivate;extTarget=Math.round(extBase*(key==="driver"?.28:.32));metricLabel="자가용 승용 보유"}if(key==="newcar"){extBase=m.newTotal;extTarget=m.newPassenger;metricLabel="8월 신규등록"}if(key==="age"){const hit=query.match(/(20|30|40|50|60|70|80|90)대/);const age=hit?hit[1]+"대":"30대";extBase=(d.ageSex202608.male[age]||0)+(d.ageSex202608.female[age]||0);extTarget=Math.round(extBase*.22);metricLabel=age+" 개인 보유"}
 const internalBase=key==="ev"?124600:key==="driver"?4100000:key==="mileage"?5300000:key==="newcar"?940000:key==="age"?1280000:5200000,internalTarget=Math.round(internalBase*(s.intScore/100)*.35);
 const send=(q=input)=>{q=q.trim();if(!q)return;const k=intent(q),x=configs[k];setKey(k);setQuery(q);setMsgs(v=>[...v,{role:"user",text:q},{role:"ai",text:`질문을 ${x.title} 관점으로 분석했습니다. 아래 결과가 이 질문에 맞춰 갱신되었습니다. 당사에서는 ‘${x.intWho}’, 외부에서는 ‘${x.extWho}’를 중심으로 근거를 비교합니다.`}]);setInput("")};
 return <main className="exec"><header className="top"><div><div className="eyebrow">AI-POWERED MARKET INTELLIGENCE</div><h1>Virtual Auto Market</h1><p className="tagline">당사 고객부터 대한민국 전체 자동차 보유자 모두를 아우르는 시장 시뮬레이터</p></div><div className="source"><Database size={14}/> 2026.01–08 · INTERNAL + EXTERNAL</div></header><section className="ask"><div className="askGlow"/><div className="askTitle"><div className="spark"><Sparkles size={18}/></div><div><b>무엇이 궁금하신가요?</b><span>질문에 따라 아래 대시보드가 자동으로 바뀝니다</span></div></div><div className="conversation">{msgs.slice(-3).map((x,i)=><div key={i} className={`bubble ${x.role}`}>{x.text}</div>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="상품, 고객군, 신차, 연령, EV 등 무엇이든 질문해보세요"/><button><Send size={17}/><span>분석하기</span></button></form><div className="examples"><button onClick={()=>send("EV 배터리 특약 반응 어떨까?")}>EV 배터리 특약</button><button onClick={()=>send("자동차보험 단독고객에게 운전자보험 연계판매하면?")}>운전자보험 연계</button><button onClick={()=>send("30대 고객 대상으로 신상품 내면 어떨까?")}>30대 시장</button><button onClick={()=>send("최근 신차 시장 기회가 어디 있어?")}>신차 시장</button></div></section>
 <section className="summary"><div className="summaryHead"><div className="resultIcon"><Layers3/></div><div><span>ANALYSIS FOR · “{query}”</span><h2>{s.title}</h2><p>{s.condition}</p></div><b>DYNAMIC RESULT</b></div><div className="compare"><article className="side internal"><div className="sideHead"><div className="sideIcon"><Building2/></div><div><span>OUR CUSTOMERS</span><h3>당사 고객 반응</h3></div><b className="badge">INTERNAL · MOCK</b></div><div className="headline"><strong>{s.intScore}<small>/100</small></strong><div><b>{s.intLabel}</b><span>고객 단위 분석 영역</span></div></div><div className="target"><Target/><div><span>핵심 타깃</span><b>{s.intWho}</b></div></div><div className="evidence"><b>이 질문에서 사용한 근거</b>{s.intReasons.map((x,i)=><p key={i}><i>{i+1}</i>{x}</p>)}</div><div className="numbers"><div><span>분석 모수 · MOCK</span><b>{fmt(internalBase)}명</b></div><div><span>우선 타깃 · MOCK</span><b>{fmt(internalTarget)}명</b></div></div></article><div className="vs"><span>VS</span></div><article className="side external"><div className="sideHead"><div className="sideIcon"><Globe2/></div><div><span>KOREA AUTO MARKET</span><h3>외부 시장 반응</h3></div><b className="badge observed">OBSERVED + SYNTHETIC</b></div><div className="headline"><strong>{s.extScore}<small>/100</small></strong><div><b>{s.extLabel}</b><span>공식 시장통계 기반 분석 영역</span></div></div><div className="target"><Target/><div><span>핵심 시장</span><b>{s.extWho}</b></div></div><div className="evidence"><b>이 질문에서 사용한 근거</b>{s.extReasons.map((x,i)=><p key={i}><i>{i+1}</i>{x}</p>)}</div><div className="numbers"><div><span>{metricLabel}</span><b>{fmt(extBase)}대</b></div><div><span>{key==="newcar"?"승용 신규등록":"탐색 시장 · SYNTHETIC"}</span><b>{fmt(extTarget)}대</b></div></div></article></div><div className="marketStrip"><TrendingUp/><div><span>2026 MARKET PULSE · OBSERVED</span><b>1월 {fmt(trend[0].total)}대 → 8월 {fmt(trend[7].total)}대</b></div><div><span>월 신규등록 최고</span><b>{fmt(Math.max(...trend.map(x=>x.new)))}대</b></div><div><span>현재 EV 승용·비사업용</span><b>{fmt(m.evPassengerPrivate)}대</b></div></div><div className="executive"><ShieldCheck/><div><span>EXECUTIVE TAKEAWAY</span><p><b>현재 결과는 입력한 질문에 따라 분석 대상·시장 모수·타깃·근거가 함께 바뀝니다.</b> 당사 영역은 실데이터가 들어오면 MOCK을 교체하고, 외부 영역은 업로드된 공식 통계를 계속 확장합니다.</p></div></div></section><button className="detailBtn" onClick={()=>setDetail(!detail)}>{detail?"상세 정보 닫기":"데이터 · 분석 구조 보기"}{detail?<ChevronUp/>:<ChevronDown/>}</button>{detail&&<section className="details"><div><b>INTERNAL CUSTOMER UNIVERSE</b><p>고객·차량·주행·사고·계약·특약·갱신·디지털 행동을 질의에 맞게 선택하는 구조입니다. 현재 내부값은 MOCK입니다.</p></div><div><b>EXTERNAL MARKET UNIVERSE</b><p>업로드한 2026년 1~8월 자동차 등록통계를 연결했습니다. 총 등록·승용·신규등록 시계열과 성·연령, EV 시장값을 질의별로 사용합니다.</p></div><div><b>AI ORCHESTRATION</b><p>자연어 → 의도/조건 → 필요한 데이터 선택 → Internal/External 각각 분석 → 비교 대시보드 재구성 → 설명 순서입니다.</p></div></section>}</main>}
